name: bmi_calculator
description: A new Flutter application.

version: 5.0.0+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^8.4.0
  sqflite: ^1.3.1+1
  path: ^1.7.0
  lottie: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
